apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: express-server.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                # Reference to a Service name, also specified in the Rollout spec.strategy.canary.stableService field
                name: express-app-svc
                port:
                  number: 3000  # Corrected the indentation