apiVersion: v1  # Added missing line
kind: Service
metadata:
  name: express-app-svc
spec:
  ports:
    - port: 3000  # The port exposed on nodes
      targetPort: port-3000  # Corrected the indentation
      protocol: TCP
      name: port-3000
  selector:
    app: express-app